### ISSUE TITLE
Telepathy not receiving IRC messages

### ISSUE THREAD

**Issue by sanderfoobar** [maemo-leste/conversations#11]
1. In a clean VM
2. Connect to IRC via Hildon's settings (`Settings->IM->Add IRC`)
3. Install latest conversations (with a clean `el-v1.db`)
4. Send a message to whatever you connected to IRC
5. `tp.cpp::onMessageReceived` not getting called
6. `tp.cpp::onAccReady` reports `isOnline: false`

**Comment by MerlijnWajer** [comment]
Reported confirmed that this was related to the environment being not from Leste, and dbus etc was missing from it. :)
