### ISSUE TITLE
Feature: filter overview

### ISSUE THREAD

**Issue by sanderfoobar** [maemo-leste/conversations#9]
Wizzup writes:

> Ability to only show message overview for specific telepathy account (sms, irc1, irc2, xmpp1, slack1, etc)

### to-do:

1. How to know which TP accounts are available?
2. How to change the rtcom query such that one can filter on individual TP accounts?
3. UI-wise, facilitate an (theoretically) endless amount of accounts

**Comment by MerlijnWajer** [comment]
So for (1), I think the Tp::AccountManager interface has methods to get all accounts (be that valid, online, active, all, etc): https://telepathy.freedesktop.org/doc/telepathy-qt/a07532.html#afcbeaa97f26550e011089f3a17ea1377

My recent changes to the `telep` branch also make use of this manager.

Of course, if there is history from an account that doesn't exist any more, this could potentially cause some trouble.

Filtering by TP account can make sense, but we could also filter by service id in combination with the `local_id` (from the rtcom database), e.g.:

```
sqlite> select distinct local_uid from events where local_uid not like '%ofono%';
ring/tel/ring
sofiasip/sip/merlijnwajer_40ekiga_2enet0
spirit/skype/wizzy_2e_2e0
sofiasip/sip/sip_2exs4all_2enl0
idle/irc/fremantle0
idle/irc/leste
gabble/jabber/merlijn@jabber.org
haze/jabber/merlijn@jabber.org
gabble/jabber/merlijn@conversations.im
```

(2)

**Comment by MerlijnWajer** [comment]
So these `local_uid`'s as far as I know are not necessarily a 1:1 mapping to Telepathy, but I did write code in the `telep` branch to try to do that. The `local_uid` is kind of canonical, so it's something like `cmName()/protocolName()/displayName()`. Whether this is future proof I don't know.

**Comment by MerlijnWajer** [comment]
There is some code in `Sender::sendMessage` that tries to find the Tp accounts for a rtcom identifier, I think.
